### ISSUE TITLE
Day 15. Part 2

### ISSUE THREAD

**Issue by catz** [gchan/advent-of-code-ruby#1]
Hello Gordon,

Stuck a little with part 2. My solution looks similar to yours. I used set for visited caves too and had to remove it to get correct answer. But something is not right here.
With your solution & my data https://gist.github.com/catz/1e813831b8f451e136bcfa227a377033
I'm getting result = 2942, but this result is incorrect and should be 2938.

This is something related to incorrect work with visited set but can't figure out what. 
Not sure you're interested in this , but anyway :)

Hope you have great holidays.
Roman

**Comment by gchan** [comment]
Hey Roman (@catz)!

I fixed the bug in my solution by correcting my implementation Dijkstra's algorithm. 
https://github.com/gchan/advent-of-code-ruby/commit/5b3144522fbfe8b0ef9bfd160ed3c5a237c852df#diff-6a654b20ca780b08a9c8b9fb6f33fadf06310b7e761277670599316ff1aea450R52-R53

The issue was due to the code not retrieving the node with the minimal distance first. I've seen solutions implement a priority queue which I expect would improve the current run time of ~28 secs on my machine.

Thanks for bringing this to my attention!

Gordon
